### ISSUE TITLE
Recomendação

### ISSUE THREAD

**Issue by Guilmoraes** [joaquim-almeida/Estudo-Java-Web#1]
Recomendo muito que você aprenda usando spring, todo mundo está usando. Digo por experiencia propria que ele é muito bom.

**Comment by joaquim-almeida** [comment]
anotado!!!

**Comment by joaquim-almeida** [comment]
e neste caso também vale a pena o aprendizado do jersey?

**Comment by Guilmoraes** [comment]
Se eu fosse você estudaria usando o JHipster, pois muitas vezes em empresas você vai criar o projeto usando ele, pois ele trás bastante coisa pronta que são bem profundas para quem está estudando, e lá no site deles eles explicam toda a estrutura.
https://www.devmedia.com.br/introducao-ao-framework-jhipster/34043
Esse tutorial deve ajudar.

**Comment by joaquim-almeida** [comment]
Caramba!!

Muito obrigado mesmo!!!
